name: Make Release from Master

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get mod version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'info.txt'
          prop_path: 'ModVersion'
      - name: Prepare folder
        run: mkdir Wrinkler-Popper && mv -t ./Wrinkler-Popper info.txt main.js LICENSE.md
      - name: Zip Folder
        run: zip -r Wrinkler-Popper-R${{steps.version.outputs.prop}} Wrinkler-Popper
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Wrinkler-Popper-R${{steps.version.outputs.prop}}.zip
          tag_name: R${{steps.version.outputs.prop}}
          token: ${{ secrets.GITHUB_TOKEN }}
